name: Deploy Docs

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Build Docs
        run: |
          yarn
          yarn build
      - name: Push Resources
        run: |
          cd dist
          git config --global user.email "lihaoze.cq@gmail.com"
          git config --global user.name "lhz960904"
          git init
          git add .
          git commit -m "deploy docs"
          git push -f git@github.com:super-wall/dynamic-form-website.git master
