name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Create local changes
        run: |
          npm install
          npm run build
      - name: Commit files
        run: |
          git config --local user.email "lihaoze.cq@gmail.com"
          git config --local user.name "lhz960904"
          git commit -m "deploy docs" -a
          git push -f https://github.com/super-wall/dynamic-form-website.git master
